theme:
  regular:    [220, 220, 220]
  defclass:   [203, 191, 255]
  construct:  [143, 143, 245]
  function:   [102, 204, 255]
  member:     [102, 204, 255]
  self:       [102, 204, 255]
  string:     [255, 112, 87]
  numeric:    [255, 153, 102]
  operator:   [255, 218, 179]
  background: [0, 51, 77]
  comment:    [130, 176, 201]

background:
  blockratio: 3 # other: mean gray
  edgeratio:  5 # other: black
  edgewidth:  8
  edgebands:  8
  bgndbands:  [4, 16] # band, bgnd
  actratio:   3

dimensions:
  resolution: [3200, 1800]
  blocksize:  [2400, 1672]
  lineheight: 1.2

video:
  fps:    16
  chps:   16
  fourcc: MJPG
  ext:    avi

font: System/Library/Fonts/Menlo.ttc
fontheight: 40
fontratio:  0.6
tabwidth: 4
